# Task 1:

Assignment 13
Read the following data set: https://archive.ics.uci.edu/ml/machine-learning-databases/adult/
Rename the columns as per the description from this file: https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.names
Task:  Create a sql db from adult dataset and name it sqladb
        1.Select 10 records from the adult sqladb
        2.Show me the average hours per week of all men who are working in private sector
        3.Show me the frequency table for education, occupation and relationship, separately
        4.Are there any people who are married, working in private sector and having a masters degree
        5.What is the average, minimum and maximum age group for people working in different sectors
        6.Calculate age distribution by country
        7.Compute a new column as 'Net-Capital-Gain' from the two columns 'capital-gain' and 'capital-loss'

In [1]:

import pandas as pd
import numpy as np
import sqlite3

In [2]:
url= "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"
df= pd.read_csv(url) 
df.head()

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [3]:
df.columns = ["age","workclass","fnlwgt","education","education_num","marital_status","occupation","relationship","race",
             "sex","capital_gain","capital_loss","hours_per_week","native_country","income_class"]
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income_class
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [4]:
df.shape

(32560, 15)

In [5]:
from sqlalchemy import create_engine
from pandasql import sqldf

engine = create_engine("sqlite://", echo= False) # Creating engine

df.to_sql("sqladb", engine,chunksize=1, if_exists='replace')

In [6]:
engine.execute("select * from sqladb limit 5;").fetchall()

[(0, 50, ' Self-emp-not-inc', 83311, ' Bachelors', 13, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 13, ' United-States', ' <=50K'),
 (1, 38, ' Private', 215646, ' HS-grad', 9, ' Divorced', ' Handlers-cleaners', ' Not-in-family', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K'),
 (2, 53, ' Private', 234721, ' 11th', 7, ' Married-civ-spouse', ' Handlers-cleaners', ' Husband', ' Black', ' Male', 0, 0, 40, ' United-States', ' <=50K'),
 (3, 28, ' Private', 338409, ' Bachelors', 13, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' Black', ' Female', 0, 0, 40, ' Cuba', ' <=50K'),
 (4, 37, ' Private', 284582, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Wife', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')]

In [7]:
engine.execute('SELECT avg(hours_per_week) as [Average Hrs/week] FROM sqladb Group BY workclass="Private";').fetchall()

[(40.437469287469284,)]

In [14]:
print(' the frequency table for Education Frequency Table')

engine.execute('SELECT education, COUNT(*) AS Frequency FROM sqladb GROUP BY education;').fetchall()

 the frequency table for Education Frequency Table

[(' 10th', 933),
 (' 11th', 1175),
 (' 12th', 433),
 (' 1st-4th', 168),
 (' 5th-6th', 333),
 (' 7th-8th', 646),
 (' 9th', 514),
 (' Assoc-acdm', 1067),
 (' Assoc-voc', 1382),
 (' Bachelors', 5354),
 (' Doctorate', 413),
 (' HS-grad', 10501),
 (' Masters', 1723),
 (' Preschool', 51),
 (' Prof-school', 576),
 (' Some-college', 7291)]

In [15]:
print('The frequency table for Occupation Frequency Table')

engine.execute('SELECT occupation, COUNT(*) AS Frequency FROM sqladb GROUP BY occupation;').fetchall()

The frequency table for Occupation Frequency Table

[(' ?', 1843),
 (' Adm-clerical', 3769),
 (' Armed-Forces', 9),
 (' Craft-repair', 4099),
 (' Exec-managerial', 4066),
 (' Farming-fishing', 994),
 (' Handlers-cleaners', 1370),
 (' Machine-op-inspct', 2002),
 (' Other-service', 3295),
 (' Priv-house-serv', 149),
 (' Prof-specialty', 4140),
 (' Protective-serv', 649),
 (' Sales', 3650),
 (' Tech-support', 928),
 (' Transport-moving', 1597)]

In [16]:
print(' The frequency table for Relationship Frequency Table')

engine.execute('SELECT relationship, COUNT(*) AS Frequency FROM sqladb GROUP BY relationship;').fetchall()

 The frequency table for Relationship Frequency Table

[(' Husband', 13193),
 (' Not-in-family', 8304),
 (' Other-relative', 981),
 (' Own-child', 5068),
 (' Unmarried', 3446),
 (' Wife', 1568)]

In [18]:
print("The people who are married, working in private sector and having a masters degree are")

engine.execute('SELECT count(*) FROM sqladb WHERE education=" Masters" AND workclass=" Private" AND marital_status=" Married-civ-spouse";').fetchall()

The people who are married, working in private sector and having a masters degree are

[(531,)]

In [20]:
print(" The average, minimum and maximum age group for people working in different sectors  are")

engine.execute("SELECT occupation, Min(age), Max(age), Avg(age) FROM sqladb Group By occupation;").fetchall()

 The average, minimum and maximum age group for people working in different sectors  are

[(' ?', 17, 90, 40.882799782962564),
 (' Adm-clerical', 17, 90, 36.96391615813213),
 (' Armed-Forces', 23, 46, 30.22222222222222),
 (' Craft-repair', 17, 90, 39.03147109050988),
 (' Exec-managerial', 17, 90, 42.16920806689621),
 (' Farming-fishing', 17, 90, 41.2112676056338),
 (' Handlers-cleaners', 17, 90, 32.16569343065694),
 (' Machine-op-inspct', 17, 90, 37.71528471528472),
 (' Other-service', 17, 90, 34.94962063732929),
 (' Priv-house-serv', 17, 81, 41.7248322147651),
 (' Prof-specialty', 17, 90, 40.51763285024155),
 (' Protective-serv', 17, 90, 38.9537750385208),
 (' Sales', 17, 90, 37.353972602739724),
 (' Tech-support', 17, 73, 37.022629310344826),
 (' Transport-moving', 17, 90, 40.19787100814026)]

# Task 2:

Assignment 14.1
Read the following data set: https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data Task:
Create an sqlalchemy engine using a sample from the data set
           1.Write two basic update queries
           2.Write two delete queries
           3.Write two filter queries
           4.Write two function queries

In [2]:
import numpy as np
import pandas as pd
import sqlalchemy
import sqlite3

In [3]:
sqlalchemy.__version__   #A quick check to verify that we are on at least version 1.2 of SQLAlchemy:

'1.2.7'

In [4]:
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data")
df

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
5,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
6,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
7,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
8,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
9,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
10,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
11,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
12,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
13,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
14,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
15,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
16,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
17,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
18,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
19,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
20,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
21,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
22,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
23,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
24,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
25,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
26,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
27,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
28,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
29,23,Local-gov,190709,Assoc-acdm,12,Never-married,Protective-serv,Not-in-family,White,Male,0,0,52,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32530,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32531,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32532,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32533,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
32534,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
32535,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32536,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
32537,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32538,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32539,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32540,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K
32541,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K
32542,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32543,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
32544,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32545,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32546,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
32547,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32548,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32549,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32550,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32551,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32552,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32553,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32554,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32555,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32556,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32557,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32558,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32559,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [5]:
df.columns = ["age","workclass","fnlwgt","education","education_num","marital_status","occupation","relationship","race",
             "sex","capital_gain","capital_loss","hours_per_week","native_country","income_class"]
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income_class
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [6]:
from sqlalchemy import create_engine

engine = create_engine('sqlite://', echo=False)  # Creating engine

df.to_sql("sqladb",con=engine,chunksize=1, if_exists='replace')

In [7]:
connection  = sqlite3.connect('sqladb')

cursor = connection.cursor()

In [9]:
print("\n 1. Create an sqlalchemy engine using a sample from the data set\n",'-'*80, sep='')

engine.execute("SELECT * FROM sqladb Limit 5").fetchall()

 1. Create an sqlalchemy engine using a sample from the data set
--------------------------------------------------------------------------------

[(0, 50, ' Self-emp-not-inc', 83311, ' Bachelors', 13, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 13, ' United-States', ' <=50K'),
 (1, 38, ' Private', 215646, ' HS-grad', 9, ' Divorced', ' Handlers-cleaners', ' Not-in-family', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K'),
 (2, 53, ' Private', 234721, ' 11th', 7, ' Married-civ-spouse', ' Handlers-cleaners', ' Husband', ' Black', ' Male', 0, 0, 40, ' United-States', ' <=50K'),
 (3, 28, ' Private', 338409, ' Bachelors', 13, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' Black', ' Female', 0, 0, 40, ' Cuba', ' <=50K'),
 (4, 37, ' Private', 284582, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Wife', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')]

In [24]:
print("\n 2. First Update (Changing Private workclass to Updated)\n",'-'*80, sep='')

engine.execute('UPDATE sqladb SET marital_status = "Updated" WHERE marital_status = " Divorced"')
engine.execute("SELECT * FROM sqladb").fetchall()

 2. First Update (Changing Private workclass to Updated)
--------------------------------------------------------------------------------

[(0, 50, ' Self-emp-not-inc', 83311, ' Bachelors', 13, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 13, 'America', ' <=50K'),
 (1, 38, 'Updated', 215646, ' HS-grad', 9, 'Updated', ' Handlers-cleaners', ' Not-in-family', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (2, 53, 'Updated', 234721, ' 11th', 7, ' Married-civ-spouse', ' Handlers-cleaners', ' Husband', ' Black', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (3, 28, 'Updated', 338409, ' Bachelors', 13, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' Black', ' Female', 0, 0, 40, ' Cuba', ' <=50K'),
 (5, 49, 'Updated', 160187, ' 9th', 5, ' Married-spouse-absent', ' Other-service', ' Not-in-family', ' Black', ' Female', 0, 0, 16, ' Jamaica', ' <=50K'),
 (6, 52, ' Self-emp-not-inc', 209642, ' HS-grad', 9, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, 'America', ' >50K'),
 (8, 42, 'Updated', 159449, ' Bachelors', 13, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 5178, 0, 40, 'America', ' >50K'),
 (9, 37, 'Updated', 280464, ' Some-college', 10, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' Black', ' Male', 0, 0, 80, 'America', ' >50K'),
 (10, 30, ' State-gov', 141297, ' Bachelors', 13, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 40, ' India', ' >50K'),
 (11, 23, 'Updated', 122272, ' Bachelors', 13, ' Never-married', ' Adm-clerical', ' Own-child', ' White', ' Female', 0, 0, 30, 'America', ' <=50K'),
 (12, 32, 'Updated', 205019, ' Assoc-acdm', 12, ' Never-married', ' Sales', ' Not-in-family', ' Black', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (13, 40, 'Updated', 121772, ' Assoc-voc', 11, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 40, ' ?', ' >50K'),
 (14, 34, 'Updated', 245487, ' 7th-8th', 4, ' Married-civ-spouse', ' Transport-moving', ' Husband', ' Amer-Indian-Eskimo', ' Male', 0, 0, 45, ' Mexico', ' <=50K'),
 (15, 25, ' Self-emp-not-inc', 176756, ' HS-grad', 9, ' Never-married', ' Farming-fishing', ' Own-child', ' White', ' Male', 0, 0, 35, 'America', ' <=50K'),
 (16, 32, 'Updated', 186824, ' HS-grad', 9, ' Never-married', ' Machine-op-inspct', ' Unmarried', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (17, 38, 'Updated', 28887, ' 11th', 7, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (19, 40, 'Updated', 193524, ' Doctorate', 16, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 60, 'America', ' >50K'),
 (20, 54, 'Updated', 302146, ' HS-grad', 9, ' Separated', ' Other-service', ' Unmarried', ' Black', ' Female', 0, 0, 20, 'America', ' <=50K'),
 (21, 35, ' Federal-gov', 76845, ' 9th', 5, ' Married-civ-spouse', ' Farming-fishing', ' Husband', ' Black', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (22, 43, 'Updated', 117037, ' 11th', 7, ' Married-civ-spouse', ' Transport-moving', ' Husband', ' White', ' Male', 0, 2042, 40, 'America', ' <=50K'),
 (23, 59, 'Updated', 109015, ' HS-grad', 9, 'Updated', ' Tech-support', ' Unmarried', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (24, 56, ' Local-gov', 216851, ' Bachelors', 13, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' >50K'),
 (25, 19, 'Updated', 168294, ' HS-grad', 9, ' Never-married', ' Craft-repair', ' Own-child', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (26, 54, ' ?', 180211, ' Some-college', 10, ' Married-civ-spouse', ' ?', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 60, ' South', ' >50K'),
 (27, 39, 'Updated', 367260, ' HS-grad', 9, 'Updated', ' Exec-managerial', ' Not-in-family', ' White', ' Male', 0, 0, 80, 'America', ' <=50K'),
 (28, 49, 'Updated', 193366, ' HS-grad', 9, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (29, 23, ' Local-gov', 190709, ' Assoc-acdm', 12, ' Never-married', ' Protective-serv', ' Not-in-family', ' White', ' Male', 0, 0, 52, 'America', ' <=50K'),
 (30, 20, 'Updated', 266015, ' Some-college', 10, ' Never-married', ' Sales', ' Own-child', ' Black', ' Male', 0, 0, 44, 'America', ' <=50K'),
 (31, 45, 'Updated', 386940, ' Bachelors', 13, 'Updated', ' Exec-managerial', ' Own-child', ' White', ' Male', 0, 1408, 40, 'America', ' <=50K'),
 (32, 30, ' Federal-gov', 59951, ' Some-college', 10, ' Married-civ-spouse', ' Adm-clerical', ' Own-child', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (33, 22, ' State-gov', 311512, ' Some-college', 10, ' Married-civ-spouse', ' Other-service', ' Husband', ' Black', ' Male', 0, 0, 15, 'America', ' <=50K'),
 (34, 48, 'Updated', 242406, ' 11th', 7, ' Never-married', ' Machine-op-inspct', ' Unmarried', ' White', ' Male', 0, 0, 40, ' Puerto-Rico', ' <=50K'),
 (35, 21, 'Updated', 197200, ' Some-college', 10, ' Never-married', ' Machine-op-inspct', ' Own-child', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (36, 19, 'Updated', 544091, ' HS-grad', 9, ' Married-AF-spouse', ' Adm-clerical', ' Wife', ' White', ' Female', 0, 0, 25, 'America', ' <=50K'),
 (37, 31, 'Updated', 84154, ' Some-college', 10, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 38, ' ?', ' >50K'),
 (38, 48, ' Self-emp-not-inc', 265477, ' Assoc-acdm', 12, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (39, 31, 'Updated', 507875, ' 9th', 5, ' Married-civ-spouse', ' Machine-op-inspct', ' Husband', ' White', ' Male', 0, 0, 43, 'America', ' <=50K'),
 (40, 53, ' Self-emp-not-inc', 88506, ' Bachelors', 13, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (41, 24, 'Updated', 172987, ' Bachelors', 13, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (42, 49, 'Updated', 94638, ' HS-grad', 9, ' Separated', ' Adm-clerical', ' Unmarried', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (43, 25, 'Updated', 289980, ' HS-grad', 9, ' Never-married', ' Handlers-cleaners', ' Not-in-family', ' White', ' Male', 0, 0, 35, 'America', ' <=50K'),
 (44, 57, ' Federal-gov', 337895, ' Bachelors', 13, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Black', ' Male', 0, 0, 40, 'America', ' >50K'),
 (45, 53, 'Updated', 144361, ' HS-grad', 9, ' Married-civ-spouse', ' Machine-op-inspct', ' Husband', ' White', ' Male', 0, 0, 38, 'America', ' <=50K'),
 (47, 41, ' State-gov', 101603, ' Assoc-voc', 11, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (48, 29, 'Updated', 271466, ' Assoc-voc', 11, ' Never-married', ' Prof-specialty', ' Not-in-family', ' White', ' Male', 0, 0, 43, 'America', ' <=50K'),
 (49, 25, 'Updated', 32275, ' Some-college', 10, ' Married-civ-spouse', ' Exec-managerial', ' Wife', ' Other', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (50, 18, 'Updated', 226956, ' HS-grad', 9, ' Never-married', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 30, ' ?', ' <=50K'),
 (51, 47, 'Updated', 51835, ' Prof-school', 15, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 0, 1902, 60, ' Honduras', ' >50K'),
 (52, 50, ' Federal-gov', 251585, ' Bachelors', 13, 'Updated', ' Exec-managerial', ' Not-in-family', ' White', ' Male', 0, 0, 55, 'America', ' >50K'),
 (53, 47, ' Self-emp-inc', 109832, ' HS-grad', 9, 'Updated', ' Exec-managerial', ' Not-in-family', ' White', ' Male', 0, 0, 60, 'America', ' <=50K'),
 (54, 43, 'Updated', 237993, ' Some-college', 10, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' >50K'),
 (55, 46, 'Updated', 216666, ' 5th-6th', 3, ' Married-civ-spouse', ' Machine-op-inspct', ' Husband', ' White', ' Male', 0, 0, 40, ' Mexico', ' <=50K'),
 (56, 35, 'Updated', 56352, ' Assoc-voc', 11, ' Married-civ-spouse', ' Other-service', ' Husband', ' White', ' Male', 0, 0, 40, ' Puerto-Rico', ' <=50K'),
 (57, 41, 'Updated', 147372, ' HS-grad', 9, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' White', ' Male', 0, 0, 48, 'America', ' <=50K'),
 (58, 30, 'Updated', 188146, ' HS-grad', 9, ' Married-civ-spouse', ' Machine-op-inspct', ' Husband', ' White', ' Male', 5013, 0, 40, 'America', ' <=50K'),
 (59, 30, 'Updated', 59496, ' Bachelors', 13, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 2407, 0, 40, 'America', ' <=50K'),
 (60, 32, ' ?', 293936, ' 7th-8th', 4, ' Married-spouse-absent', ' ?', ' Not-in-family', ' White', ' Male', 0, 0, 40, ' ?', ' <=50K'),
 (61, 48, 'Updated', 149640, ' HS-grad', 9, ' Married-civ-spouse', ' Transport-moving', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (62, 42, 'Updated', 116632, ' Doctorate', 16, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 45, 'America', ' >50K'),
 (63, 29, 'Updated', 105598, ' Some-college', 10, 'Updated', ' Tech-support', ' Not-in-family', ' White', ' Male', 0, 0, 58, 'America', ' <=50K'),
 (64, 36, 'Updated', 155537, ' HS-grad', 9, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (65, 28, 'Updated', 183175, ' Some-college', 10, 'Updated', ' Adm-clerical', ' Not-in-family', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (66, 53, 'Updated', 169846, ' HS-grad', 9, ' Married-civ-spouse', ' Adm-clerical', ' Wife', ' White', ' Female', 0, 0, 40, 'America', ' >50K'),
 (67, 49, ' Self-emp-inc', 191681, ' Some-college', 10, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' >50K'),
 (68, 25, ' ?', 200681, ' Some-college', 10, ' Never-married', ' ?', ' Own-child', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (69, 19, 'Updated', 101509, ' Some-college', 10, ' Never-married', ' Prof-specialty', ' Own-child', ' White', ' Male', 0, 0, 32, 'America', ' <=50K'),
 (70, 31, 'Updated', 309974, ' Bachelors', 13, ' Separated', ' Sales', ' Own-child', ' Black', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (71, 29, ' Self-emp-not-inc', 162298, ' Bachelors', 13, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 70, 'America', ' >50K'),
 (72, 23, 'Updated', 211678, ' Some-college', 10, ' Never-married', ' Machine-op-inspct', ' Not-in-family', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (73, 79, 'Updated', 124744, ' Some-college', 10, ' Married-civ-spouse', ' Prof-specialty', ' Other-relative', ' White', ' Male', 0, 0, 20, 'America', ' <=50K'),
 (74, 27, 'Updated', 213921, ' HS-grad', 9, ' Never-married', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 40, ' Mexico', ' <=50K'),
 (75, 40, 'Updated', 32214, ' Assoc-acdm', 12, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (76, 67, ' ?', 212759, ' 10th', 6, ' Married-civ-spouse', ' ?', ' Husband', ' White', ' Male', 0, 0, 2, 'America', ' <=50K'),
 (77, 18, 'Updated', 309634, ' 11th', 7, ' Never-married', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 22, 'America', ' <=50K'),
 (78, 31, ' Local-gov', 125927, ' 7th-8th', 4, ' Married-civ-spouse', ' Farming-fishing', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (79, 18, 'Updated', 446839, ' HS-grad', 9, ' Never-married', ' Sales', ' Not-in-family', ' White', ' Male', 0, 0, 30, 'America', ' <=50K'),
 (80, 52, 'Updated', 276515, ' Bachelors', 13, ' Married-civ-spouse', ' Other-service', ' Husband', ' White', ' Male', 0, 0, 40, ' Cuba', ' <=50K'),
 (81, 46, 'Updated', 51618, ' HS-grad', 9, ' Married-civ-spouse', ' Other-service', ' Wife', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (82, 59, 'Updated', 159937, ' HS-grad', 9, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 48, 'America', ' <=50K'),
 (83, 44, 'Updated', 343591, ' HS-grad', 9, 'Updated', ' Craft-repair', ' Not-in-family', ' White', ' Female', 14344, 0, 40, 'America', ' >50K'),
 (84, 53, 'Updated', 346253, ' HS-grad', 9, 'Updated', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 35, 'America', ' <=50K'),
 (85, 49, ' Local-gov', 268234, ' HS-grad', 9, ' Married-civ-spouse', ' Protective-serv', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' >50K'),
 (87, 30, 'Updated', 54334, ' 9th', 5, ' Never-married', ' Sales', ' Not-in-family', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (88, 43, ' Federal-gov', 410867, ' Doctorate', 16, ' Never-married', ' Prof-specialty', ' Not-in-family', ' White', ' Female', 0, 0, 50, 'America', ' >50K'),
 (89, 57, 'Updated', 249977, ' Assoc-voc', 11, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (90, 37, 'Updated', 286730, ' Some-college', 10, 'Updated', ' Craft-repair', ' Unmarried', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (91, 28, 'Updated', 212563, ' Some-college', 10, 'Updated', ' Machine-op-inspct', ' Unmarried', ' Black', ' Female', 0, 0, 25, 'America', ' <=50K'),
 (92, 30, 'Updated', 117747, ' HS-grad', 9, ' Married-civ-spouse', ' Sales', ' Wife', ' Asian-Pac-Islander', ' Female', 0, 1573, 35, ' ?', ' <=50K'),
 (93, 34, ' Local-gov', 226296, ' Bachelors', 13, ' Married-civ-spouse', ' Protective-serv', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' >50K'),
 (94, 29, ' Local-gov', 115585, ' Some-college', 10, ' Never-married', ' Handlers-cleaners', ' Not-in-family', ' White', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (95, 48, ' Self-emp-not-inc', 191277, ' Doctorate', 16, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 1902, 60, 'America', ' >50K'),
 (96, 37, 'Updated', 202683, ' Some-college', 10, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 48, 'America', ' >50K'),
 (97, 48, 'Updated', 171095, ' Assoc-acdm', 12, 'Updated', ' Exec-managerial', ' Unmarried', ' White', ' Female', 0, 0, 40, ' England', ' <=50K'),
 (98, 32, ' Federal-gov', 249409, ' HS-grad', 9, ' Never-married', ' Other-service', ' Own-child', ' Black', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (100, 44, 'Updated', 198282, ' Bachelors', 13, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 60, 'America', ' >50K'),
 (102, 20, 'Updated', 188300, ' Some-college', 10, ' Never-married', ' Tech-support', ' Own-child', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (103, 29, 'Updated', 103432, ' HS-grad', 9, ' Never-married', ' Craft-repair', ' Not-in-family', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (104, 32, ' Self-emp-inc', 317660, ' HS-grad', 9, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 7688, 0, 40, 'America', ' >50K'),
 (105, 17, ' ?', 304873, ' 10th', 6, ' Never-married', ' ?', ' Own-child', ' White', ' Female', 34095, 0, 32, 'America', ' <=50K'),
 (106, 30, 'Updated', 194901, ' 11th', 7, ' Never-married', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (107, 31, ' Local-gov', 189265, ' HS-grad', 9, ' Never-married', ' Adm-clerical', ' Not-in-family', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (108, 42, 'Updated', 124692, ' HS-grad', 9, ' Married-civ-spouse', ' Handlers-cleaners', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (109, 24, 'Updated', 432376, ' Bachelors', 13, ' Never-married', ' Sales', ' Other-relative', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (110, 38, 'Updated', 65324, ' Prof-school', 15, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' >50K'),
 (111, 56, ' Self-emp-not-inc', 335605, ' HS-grad', 9, ' Married-civ-spouse', ' Other-service', ' Husband', ' White', ' Male', 0, 1887, 50, ' Canada', ' >50K'),
 (112, 28, 'Updated', 377869, ' Some-college', 10, ' Married-civ-spouse', ' Sales', ' Wife', ' White', ' Female', 4064, 0, 25, 'America', ' <=50K'),
 (113, 36, 'Updated', 102864, ' HS-grad', 9, ' Never-married', ' Machine-op-inspct', ' Own-child', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (114, 53, 'Updated', 95647, ' 9th', 5, ' Married-civ-spouse', ' Handlers-cleaners', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (115, 56, ' Self-emp-inc', 303090, ' Some-college', 10, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (116, 49, ' Local-gov', 197371, ' Assoc-voc', 11, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' Black', ' Male', 0, 0, 40, 'America', ' >50K'),
 (117, 55, 'Updated', 247552, ' Some-college', 10, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 56, 'America', ' <=50K'),
 (118, 22, 'Updated', 102632, ' HS-grad', 9, ' Never-married', ' Craft-repair', ' Not-in-family', ' White', ' Male', 0, 0, 41, 'America', ' <=50K'),
 (119, 21, 'Updated', 199915, ' Some-college', 10, ' Never-married', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (120, 40, 'Updated', 118853, ' Bachelors', 13, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 60, 'America', ' <=50K'),
 (121, 30, 'Updated', 77143, ' Bachelors', 13, ' Never-married', ' Exec-managerial', ' Own-child', ' Black', ' Male', 0, 0, 40, ' Germany', ' <=50K'),
 (122, 29, ' State-gov', 267989, ' Bachelors', 13, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' >50K'),
 (123, 19, 'Updated', 301606, ' Some-college', 10, ' Never-married', ' Other-service', ' Own-child', ' Black', ' Male', 0, 0, 35, 'America', ' <=50K'),
 (124, 47, 'Updated', 287828, ' Bachelors', 13, ' Married-civ-spouse', ' Exec-managerial', ' Wife', ' White', ' Female', 0, 0, 40, 'America', ' >50K'),
 (125, 20, 'Updated', 111697, ' Some-college', 10, ' Never-married', ' Adm-clerical', ' Own-child', ' White', ' Female', 0, 1719, 28, 'America', ' <=50K'),
 (126, 31, 'Updated', 114937, ' Assoc-acdm', 12, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' >50K'),
 (127, 35, ' ?', 129305, ' HS-grad', 9, ' Married-civ-spouse', ' ?', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (128, 39, 'Updated', 365739, ' Some-college', 10, 'Updated', ' Craft-repair', ' Not-in-family', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (129, 28, 'Updated', 69621, ' Assoc-acdm', 12, ' Never-married', ' Sales', ' Not-in-family', ' White', ' Female', 0, 0, 60, 'America', ' <=50K'),
 (130, 24, 'Updated', 43323, ' HS-grad', 9, ' Never-married', ' Other-service', ' Not-in-family', ' White', ' Female', 0, 1762, 40, 'America', ' <=50K'),
 (131, 38, ' Self-emp-not-inc', 120985, ' HS-grad', 9, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 4386, 0, 35, 'America', ' <=50K'),
 (132, 37, 'Updated', 254202, ' Bachelors', 13, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (133, 46, 'Updated', 146195, ' Assoc-acdm', 12, 'Updated', ' Tech-support', ' Not-in-family', ' Black', ' Female', 0, 0, 36, 'America', ' <=50K'),
 (135, 43, ' Self-emp-not-inc', 56920, ' HS-grad', 9, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 0, 0, 60, 'America', ' <=50K'),
 (136, 27, 'Updated', 163127, ' Assoc-voc', 11, ' Married-civ-spouse', ' Adm-clerical', ' Wife', ' White', ' Female', 0, 0, 35, 'America', ' <=50K'),
 (137, 20, 'Updated', 34310, ' Some-college', 10, ' Never-married', ' Sales', ' Own-child', ' White', ' Male', 0, 0, 20, 'America', ' <=50K'),
 (138, 49, 'Updated', 81973, ' Some-college', 10, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 40, 'America', ' >50K'),
 (139, 61, ' Self-emp-inc', 66614, ' HS-grad', 9, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (140, 27, 'Updated', 232782, ' Some-college', 10, ' Never-married', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),

In [15]:
print("\n 2. Second Update (Changing native-country from United-States to America)\n",'-'*80, sep='')

engine.execute('UPDATE sqladb SET native_country = "America" WHERE native_country = " United-States"')
engine.execute("SELECT * FROM sqladb;").fetchall()

 2. Second Update (Changing native-country from United-States to America)
--------------------------------------------------------------------------------

[(0, 50, ' Self-emp-not-inc', 83311, ' Bachelors', 13, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 13, 'America', ' <=50K'),
 (1, 38, 'Updated', 215646, ' HS-grad', 9, ' Divorced', ' Handlers-cleaners', ' Not-in-family', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (2, 53, 'Updated', 234721, ' 11th', 7, ' Married-civ-spouse', ' Handlers-cleaners', ' Husband', ' Black', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (3, 28, 'Updated', 338409, ' Bachelors', 13, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' Black', ' Female', 0, 0, 40, ' Cuba', ' <=50K'),
 (4, 37, 'Updated', 284582, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Wife', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (5, 49, 'Updated', 160187, ' 9th', 5, ' Married-spouse-absent', ' Other-service', ' Not-in-family', ' Black', ' Female', 0, 0, 16, ' Jamaica', ' <=50K'),
 (6, 52, ' Self-emp-not-inc', 209642, ' HS-grad', 9, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, 'America', ' >50K'),
 (7, 31, 'Updated', 45781, ' Masters', 14, ' Never-married', ' Prof-specialty', ' Not-in-family', ' White', ' Female', 14084, 0, 50, 'America', ' >50K'),
 (8, 42, 'Updated', 159449, ' Bachelors', 13, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 5178, 0, 40, 'America', ' >50K'),
 (9, 37, 'Updated', 280464, ' Some-college', 10, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' Black', ' Male', 0, 0, 80, 'America', ' >50K'),
 (10, 30, ' State-gov', 141297, ' Bachelors', 13, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 40, ' India', ' >50K'),
 (11, 23, 'Updated', 122272, ' Bachelors', 13, ' Never-married', ' Adm-clerical', ' Own-child', ' White', ' Female', 0, 0, 30, 'America', ' <=50K'),
 (12, 32, 'Updated', 205019, ' Assoc-acdm', 12, ' Never-married', ' Sales', ' Not-in-family', ' Black', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (13, 40, 'Updated', 121772, ' Assoc-voc', 11, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 40, ' ?', ' >50K'),
 (14, 34, 'Updated', 245487, ' 7th-8th', 4, ' Married-civ-spouse', ' Transport-moving', ' Husband', ' Amer-Indian-Eskimo', ' Male', 0, 0, 45, ' Mexico', ' <=50K'),
 (15, 25, ' Self-emp-not-inc', 176756, ' HS-grad', 9, ' Never-married', ' Farming-fishing', ' Own-child', ' White', ' Male', 0, 0, 35, 'America', ' <=50K'),
 (16, 32, 'Updated', 186824, ' HS-grad', 9, ' Never-married', ' Machine-op-inspct', ' Unmarried', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (17, 38, 'Updated', 28887, ' 11th', 7, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (18, 43, ' Self-emp-not-inc', 292175, ' Masters', 14, ' Divorced', ' Exec-managerial', ' Unmarried', ' White', ' Female', 0, 0, 45, 'America', ' >50K'),
 (19, 40, 'Updated', 193524, ' Doctorate', 16, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 60, 'America', ' >50K'),
 (20, 54, 'Updated', 302146, ' HS-grad', 9, ' Separated', ' Other-service', ' Unmarried', ' Black', ' Female', 0, 0, 20, 'America', ' <=50K'),
 (21, 35, ' Federal-gov', 76845, ' 9th', 5, ' Married-civ-spouse', ' Farming-fishing', ' Husband', ' Black', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (22, 43, 'Updated', 117037, ' 11th', 7, ' Married-civ-spouse', ' Transport-moving', ' Husband', ' White', ' Male', 0, 2042, 40, 'America', ' <=50K'),
 (23, 59, 'Updated', 109015, ' HS-grad', 9, ' Divorced', ' Tech-support', ' Unmarried', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (24, 56, ' Local-gov', 216851, ' Bachelors', 13, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' >50K'),
 (25, 19, 'Updated', 168294, ' HS-grad', 9, ' Never-married', ' Craft-repair', ' Own-child', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (26, 54, ' ?', 180211, ' Some-college', 10, ' Married-civ-spouse', ' ?', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 60, ' South', ' >50K'),
 (27, 39, 'Updated', 367260, ' HS-grad', 9, ' Divorced', ' Exec-managerial', ' Not-in-family', ' White', ' Male', 0, 0, 80, 'America', ' <=50K'),
 (28, 49, 'Updated', 193366, ' HS-grad', 9, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (29, 23, ' Local-gov', 190709, ' Assoc-acdm', 12, ' Never-married', ' Protective-serv', ' Not-in-family', ' White', ' Male', 0, 0, 52, 'America', ' <=50K'),
 (30, 20, 'Updated', 266015, ' Some-college', 10, ' Never-married', ' Sales', ' Own-child', ' Black', ' Male', 0, 0, 44, 'America', ' <=50K'),
 (31, 45, 'Updated', 386940, ' Bachelors', 13, ' Divorced', ' Exec-managerial', ' Own-child', ' White', ' Male', 0, 1408, 40, 'America', ' <=50K'),
 (32, 30, ' Federal-gov', 59951, ' Some-college', 10, ' Married-civ-spouse', ' Adm-clerical', ' Own-child', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (33, 22, ' State-gov', 311512, ' Some-college', 10, ' Married-civ-spouse', ' Other-service', ' Husband', ' Black', ' Male', 0, 0, 15, 'America', ' <=50K'),
 (34, 48, 'Updated', 242406, ' 11th', 7, ' Never-married', ' Machine-op-inspct', ' Unmarried', ' White', ' Male', 0, 0, 40, ' Puerto-Rico', ' <=50K'),
 (35, 21, 'Updated', 197200, ' Some-college', 10, ' Never-married', ' Machine-op-inspct', ' Own-child', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (36, 19, 'Updated', 544091, ' HS-grad', 9, ' Married-AF-spouse', ' Adm-clerical', ' Wife', ' White', ' Female', 0, 0, 25, 'America', ' <=50K'),
 (37, 31, 'Updated', 84154, ' Some-college', 10, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 38, ' ?', ' >50K'),
 (38, 48, ' Self-emp-not-inc', 265477, ' Assoc-acdm', 12, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (39, 31, 'Updated', 507875, ' 9th', 5, ' Married-civ-spouse', ' Machine-op-inspct', ' Husband', ' White', ' Male', 0, 0, 43, 'America', ' <=50K'),
 (40, 53, ' Self-emp-not-inc', 88506, ' Bachelors', 13, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (41, 24, 'Updated', 172987, ' Bachelors', 13, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (42, 49, 'Updated', 94638, ' HS-grad', 9, ' Separated', ' Adm-clerical', ' Unmarried', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (43, 25, 'Updated', 289980, ' HS-grad', 9, ' Never-married', ' Handlers-cleaners', ' Not-in-family', ' White', ' Male', 0, 0, 35, 'America', ' <=50K'),
 (44, 57, ' Federal-gov', 337895, ' Bachelors', 13, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Black', ' Male', 0, 0, 40, 'America', ' >50K'),
 (45, 53, 'Updated', 144361, ' HS-grad', 9, ' Married-civ-spouse', ' Machine-op-inspct', ' Husband', ' White', ' Male', 0, 0, 38, 'America', ' <=50K'),
 (46, 44, 'Updated', 128354, ' Masters', 14, ' Divorced', ' Exec-managerial', ' Unmarried', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (47, 41, ' State-gov', 101603, ' Assoc-voc', 11, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (48, 29, 'Updated', 271466, ' Assoc-voc', 11, ' Never-married', ' Prof-specialty', ' Not-in-family', ' White', ' Male', 0, 0, 43, 'America', ' <=50K'),
 (49, 25, 'Updated', 32275, ' Some-college', 10, ' Married-civ-spouse', ' Exec-managerial', ' Wife', ' Other', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (50, 18, 'Updated', 226956, ' HS-grad', 9, ' Never-married', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 30, ' ?', ' <=50K'),
 (51, 47, 'Updated', 51835, ' Prof-school', 15, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 0, 1902, 60, ' Honduras', ' >50K'),
 (52, 50, ' Federal-gov', 251585, ' Bachelors', 13, ' Divorced', ' Exec-managerial', ' Not-in-family', ' White', ' Male', 0, 0, 55, 'America', ' >50K'),
 (53, 47, ' Self-emp-inc', 109832, ' HS-grad', 9, ' Divorced', ' Exec-managerial', ' Not-in-family', ' White', ' Male', 0, 0, 60, 'America', ' <=50K'),
 (54, 43, 'Updated', 237993, ' Some-college', 10, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' >50K'),
 (55, 46, 'Updated', 216666, ' 5th-6th', 3, ' Married-civ-spouse', ' Machine-op-inspct', ' Husband', ' White', ' Male', 0, 0, 40, ' Mexico', ' <=50K'),
 (56, 35, 'Updated', 56352, ' Assoc-voc', 11, ' Married-civ-spouse', ' Other-service', ' Husband', ' White', ' Male', 0, 0, 40, ' Puerto-Rico', ' <=50K'),
 (57, 41, 'Updated', 147372, ' HS-grad', 9, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' White', ' Male', 0, 0, 48, 'America', ' <=50K'),
 (58, 30, 'Updated', 188146, ' HS-grad', 9, ' Married-civ-spouse', ' Machine-op-inspct', ' Husband', ' White', ' Male', 5013, 0, 40, 'America', ' <=50K'),
 (59, 30, 'Updated', 59496, ' Bachelors', 13, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 2407, 0, 40, 'America', ' <=50K'),
 (60, 32, ' ?', 293936, ' 7th-8th', 4, ' Married-spouse-absent', ' ?', ' Not-in-family', ' White', ' Male', 0, 0, 40, ' ?', ' <=50K'),
 (61, 48, 'Updated', 149640, ' HS-grad', 9, ' Married-civ-spouse', ' Transport-moving', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (62, 42, 'Updated', 116632, ' Doctorate', 16, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 45, 'America', ' >50K'),
 (63, 29, 'Updated', 105598, ' Some-college', 10, ' Divorced', ' Tech-support', ' Not-in-family', ' White', ' Male', 0, 0, 58, 'America', ' <=50K'),
 (64, 36, 'Updated', 155537, ' HS-grad', 9, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (65, 28, 'Updated', 183175, ' Some-college', 10, ' Divorced', ' Adm-clerical', ' Not-in-family', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (66, 53, 'Updated', 169846, ' HS-grad', 9, ' Married-civ-spouse', ' Adm-clerical', ' Wife', ' White', ' Female', 0, 0, 40, 'America', ' >50K'),
 (67, 49, ' Self-emp-inc', 191681, ' Some-college', 10, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' >50K'),
 (68, 25, ' ?', 200681, ' Some-college', 10, ' Never-married', ' ?', ' Own-child', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (69, 19, 'Updated', 101509, ' Some-college', 10, ' Never-married', ' Prof-specialty', ' Own-child', ' White', ' Male', 0, 0, 32, 'America', ' <=50K'),
 (70, 31, 'Updated', 309974, ' Bachelors', 13, ' Separated', ' Sales', ' Own-child', ' Black', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (71, 29, ' Self-emp-not-inc', 162298, ' Bachelors', 13, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 70, 'America', ' >50K'),
 (72, 23, 'Updated', 211678, ' Some-college', 10, ' Never-married', ' Machine-op-inspct', ' Not-in-family', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (73, 79, 'Updated', 124744, ' Some-college', 10, ' Married-civ-spouse', ' Prof-specialty', ' Other-relative', ' White', ' Male', 0, 0, 20, 'America', ' <=50K'),
 (74, 27, 'Updated', 213921, ' HS-grad', 9, ' Never-married', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 40, ' Mexico', ' <=50K'),
 (75, 40, 'Updated', 32214, ' Assoc-acdm', 12, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (76, 67, ' ?', 212759, ' 10th', 6, ' Married-civ-spouse', ' ?', ' Husband', ' White', ' Male', 0, 0, 2, 'America', ' <=50K'),
 (77, 18, 'Updated', 309634, ' 11th', 7, ' Never-married', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 22, 'America', ' <=50K'),
 (78, 31, ' Local-gov', 125927, ' 7th-8th', 4, ' Married-civ-spouse', ' Farming-fishing', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (79, 18, 'Updated', 446839, ' HS-grad', 9, ' Never-married', ' Sales', ' Not-in-family', ' White', ' Male', 0, 0, 30, 'America', ' <=50K'),
 (80, 52, 'Updated', 276515, ' Bachelors', 13, ' Married-civ-spouse', ' Other-service', ' Husband', ' White', ' Male', 0, 0, 40, ' Cuba', ' <=50K'),
 (81, 46, 'Updated', 51618, ' HS-grad', 9, ' Married-civ-spouse', ' Other-service', ' Wife', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (82, 59, 'Updated', 159937, ' HS-grad', 9, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 48, 'America', ' <=50K'),
 (83, 44, 'Updated', 343591, ' HS-grad', 9, ' Divorced', ' Craft-repair', ' Not-in-family', ' White', ' Female', 14344, 0, 40, 'America', ' >50K'),
 (84, 53, 'Updated', 346253, ' HS-grad', 9, ' Divorced', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 35, 'America', ' <=50K'),
 (85, 49, ' Local-gov', 268234, ' HS-grad', 9, ' Married-civ-spouse', ' Protective-serv', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' >50K'),
 (86, 33, 'Updated', 202051, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (87, 30, 'Updated', 54334, ' 9th', 5, ' Never-married', ' Sales', ' Not-in-family', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (88, 43, ' Federal-gov', 410867, ' Doctorate', 16, ' Never-married', ' Prof-specialty', ' Not-in-family', ' White', ' Female', 0, 0, 50, 'America', ' >50K'),
 (89, 57, 'Updated', 249977, ' Assoc-voc', 11, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (90, 37, 'Updated', 286730, ' Some-college', 10, ' Divorced', ' Craft-repair', ' Unmarried', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (91, 28, 'Updated', 212563, ' Some-college', 10, ' Divorced', ' Machine-op-inspct', ' Unmarried', ' Black', ' Female', 0, 0, 25, 'America', ' <=50K'),
 (92, 30, 'Updated', 117747, ' HS-grad', 9, ' Married-civ-spouse', ' Sales', ' Wife', ' Asian-Pac-Islander', ' Female', 0, 1573, 35, ' ?', ' <=50K'),
 (93, 34, ' Local-gov', 226296, ' Bachelors', 13, ' Married-civ-spouse', ' Protective-serv', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' >50K'),
 (94, 29, ' Local-gov', 115585, ' Some-college', 10, ' Never-married', ' Handlers-cleaners', ' Not-in-family', ' White', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (95, 48, ' Self-emp-not-inc', 191277, ' Doctorate', 16, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 1902, 60, 'America', ' >50K'),
 (96, 37, 'Updated', 202683, ' Some-college', 10, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 48, 'America', ' >50K'),
 (97, 48, 'Updated', 171095, ' Assoc-acdm', 12, ' Divorced', ' Exec-managerial', ' Unmarried', ' White', ' Female', 0, 0, 40, ' England', ' <=50K'),
 (98, 32, ' Federal-gov', 249409, ' HS-grad', 9, ' Never-married', ' Other-service', ' Own-child', ' Black', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (99, 76, 'Updated', 124191, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' >50K'),
 (100, 44, 'Updated', 198282, ' Bachelors', 13, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 60, 'America', ' >50K'),
 (101, 47, ' Self-emp-not-inc', 149116, ' Masters', 14, ' Never-married', ' Prof-specialty', ' Not-in-family', ' White', ' Female', 0, 0, 50, 'America', ' <=50K'),
 (102, 20, 'Updated', 188300, ' Some-college', 10, ' Never-married', ' Tech-support', ' Own-child', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (103, 29, 'Updated', 103432, ' HS-grad', 9, ' Never-married', ' Craft-repair', ' Not-in-family', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (104, 32, ' Self-emp-inc', 317660, ' HS-grad', 9, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 7688, 0, 40, 'America', ' >50K'),
 (105, 17, ' ?', 304873, ' 10th', 6, ' Never-married', ' ?', ' Own-child', ' White', ' Female', 34095, 0, 32, 'America', ' <=50K'),
 (106, 30, 'Updated', 194901, ' 11th', 7, ' Never-married', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (107, 31, ' Local-gov', 189265, ' HS-grad', 9, ' Never-married', ' Adm-clerical', ' Not-in-family', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (108, 42, 'Updated', 124692, ' HS-grad', 9, ' Married-civ-spouse', ' Handlers-cleaners', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (109, 24, 'Updated', 432376, ' Bachelors', 13, ' Never-married', ' Sales', ' Other-relative', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (110, 38, 'Updated', 65324, ' Prof-school', 15, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' >50K'),
 (111, 56, ' Self-emp-not-inc', 335605, ' HS-grad', 9, ' Married-civ-spouse', ' Other-service', ' Husband', ' White', ' Male', 0, 1887, 50, ' Canada', ' >50K'),
 (112, 28, 'Updated', 377869, ' Some-college', 10, ' Married-civ-spouse', ' Sales', ' Wife', ' White', ' Female', 4064, 0, 25, 'America', ' <=50K'),
 (113, 36, 'Updated', 102864, ' HS-grad', 9, ' Never-married', ' Machine-op-inspct', ' Own-child', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (114, 53, 'Updated', 95647, ' 9th', 5, ' Married-civ-spouse', ' Handlers-cleaners', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (115, 56, ' Self-emp-inc', 303090, ' Some-college', 10, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (116, 49, ' Local-gov', 197371, ' Assoc-voc', 11, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' Black', ' Male', 0, 0, 40, 'America', ' >50K'),
 (117, 55, 'Updated', 247552, ' Some-college', 10, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 56, 'America', ' <=50K'),
 (118, 22, 'Updated', 102632, ' HS-grad', 9, ' Never-married', ' Craft-repair', ' Not-in-family', ' White', ' Male', 0, 0, 41, 'America', ' <=50K'),
 (119, 21, 'Updated', 199915, ' Some-college', 10, ' Never-married', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (120, 40, 'Updated', 118853, ' Bachelors', 13, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 60, 'America', ' <=50K'),
 (121, 30, 'Updated', 77143, ' Bachelors', 13, ' Never-married', ' Exec-managerial', ' Own-child', ' Black', ' Male', 0, 0, 40, ' Germany', ' <=50K'),
 (122, 29, ' State-gov', 267989, ' Bachelors', 13, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' >50K'),
 (123, 19, 'Updated', 301606, ' Some-college', 10, ' Never-married', ' Other-service', ' Own-child', ' Black', ' Male', 0, 0, 35, 'America', ' <=50K'),
 (124, 47, 'Updated', 287828, ' Bachelors', 13, ' Married-civ-spouse', ' Exec-managerial', ' Wife', ' White', ' Female', 0, 0, 40, 'America', ' >50K'),
 (125, 20, 'Updated', 111697, ' Some-college', 10, ' Never-married', ' Adm-clerical', ' Own-child', ' White', ' Female', 0, 1719, 28, 'America', ' <=50K'),
 (126, 31, 'Updated', 114937, ' Assoc-acdm', 12, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' >50K'),
 (127, 35, ' ?', 129305, ' HS-grad', 9, ' Married-civ-spouse', ' ?', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (128, 39, 'Updated', 365739, ' Some-college', 10, ' Divorced', ' Craft-repair', ' Not-in-family', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (129, 28, 'Updated', 69621, ' Assoc-acdm', 12, ' Never-married', ' Sales', ' Not-in-family', ' White', ' Female', 0, 0, 60, 'America', ' <=50K'),
 (130, 24, 'Updated', 43323, ' HS-grad', 9, ' Never-married', ' Other-service', ' Not-in-family', ' White', ' Female', 0, 1762, 40, 'America', ' <=50K'),
 (131, 38, ' Self-emp-not-inc', 120985, ' HS-grad', 9, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 4386, 0, 35, 'America', ' <=50K'),
 (132, 37, 'Updated', 254202, ' Bachelors', 13, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' <=50K'),

In [17]:
print("\n 3. First delete query (Delete rows where education = Masters) \n",'-'*80, sep='')

engine.execute('DELETE FROM sqladb WHERE education = " Masters"')
engine.execute("SELECT * FROM sqladb").fetchall()

 3. First delete query (Delete rows where education = Masters)
--------------------------------------------------------------------------------

[(0, 50, ' Self-emp-not-inc', 83311, ' Bachelors', 13, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 13, 'America', ' <=50K'),
 (1, 38, 'Updated', 215646, ' HS-grad', 9, ' Divorced', ' Handlers-cleaners', ' Not-in-family', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (2, 53, 'Updated', 234721, ' 11th', 7, ' Married-civ-spouse', ' Handlers-cleaners', ' Husband', ' Black', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (3, 28, 'Updated', 338409, ' Bachelors', 13, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' Black', ' Female', 0, 0, 40, ' Cuba', ' <=50K'),
 (5, 49, 'Updated', 160187, ' 9th', 5, ' Married-spouse-absent', ' Other-service', ' Not-in-family', ' Black', ' Female', 0, 0, 16, ' Jamaica', ' <=50K'),
 (6, 52, ' Self-emp-not-inc', 209642, ' HS-grad', 9, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, 'America', ' >50K'),
 (8, 42, 'Updated', 159449, ' Bachelors', 13, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 5178, 0, 40, 'America', ' >50K'),
 (9, 37, 'Updated', 280464, ' Some-college', 10, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' Black', ' Male', 0, 0, 80, 'America', ' >50K'),
 (10, 30, ' State-gov', 141297, ' Bachelors', 13, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 40, ' India', ' >50K'),
 (11, 23, 'Updated', 122272, ' Bachelors', 13, ' Never-married', ' Adm-clerical', ' Own-child', ' White', ' Female', 0, 0, 30, 'America', ' <=50K'),
 (12, 32, 'Updated', 205019, ' Assoc-acdm', 12, ' Never-married', ' Sales', ' Not-in-family', ' Black', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (13, 40, 'Updated', 121772, ' Assoc-voc', 11, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 40, ' ?', ' >50K'),
 (14, 34, 'Updated', 245487, ' 7th-8th', 4, ' Married-civ-spouse', ' Transport-moving', ' Husband', ' Amer-Indian-Eskimo', ' Male', 0, 0, 45, ' Mexico', ' <=50K'),
 (15, 25, ' Self-emp-not-inc', 176756, ' HS-grad', 9, ' Never-married', ' Farming-fishing', ' Own-child', ' White', ' Male', 0, 0, 35, 'America', ' <=50K'),
 (16, 32, 'Updated', 186824, ' HS-grad', 9, ' Never-married', ' Machine-op-inspct', ' Unmarried', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (17, 38, 'Updated', 28887, ' 11th', 7, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (19, 40, 'Updated', 193524, ' Doctorate', 16, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 60, 'America', ' >50K'),
 (20, 54, 'Updated', 302146, ' HS-grad', 9, ' Separated', ' Other-service', ' Unmarried', ' Black', ' Female', 0, 0, 20, 'America', ' <=50K'),
 (21, 35, ' Federal-gov', 76845, ' 9th', 5, ' Married-civ-spouse', ' Farming-fishing', ' Husband', ' Black', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (22, 43, 'Updated', 117037, ' 11th', 7, ' Married-civ-spouse', ' Transport-moving', ' Husband', ' White', ' Male', 0, 2042, 40, 'America', ' <=50K'),
 (23, 59, 'Updated', 109015, ' HS-grad', 9, ' Divorced', ' Tech-support', ' Unmarried', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (24, 56, ' Local-gov', 216851, ' Bachelors', 13, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' >50K'),
 (25, 19, 'Updated', 168294, ' HS-grad', 9, ' Never-married', ' Craft-repair', ' Own-child', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (26, 54, ' ?', 180211, ' Some-college', 10, ' Married-civ-spouse', ' ?', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 60, ' South', ' >50K'),
 (27, 39, 'Updated', 367260, ' HS-grad', 9, ' Divorced', ' Exec-managerial', ' Not-in-family', ' White', ' Male', 0, 0, 80, 'America', ' <=50K'),
 (28, 49, 'Updated', 193366, ' HS-grad', 9, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (29, 23, ' Local-gov', 190709, ' Assoc-acdm', 12, ' Never-married', ' Protective-serv', ' Not-in-family', ' White', ' Male', 0, 0, 52, 'America', ' <=50K'),
 (30, 20, 'Updated', 266015, ' Some-college', 10, ' Never-married', ' Sales', ' Own-child', ' Black', ' Male', 0, 0, 44, 'America', ' <=50K'),
 (31, 45, 'Updated', 386940, ' Bachelors', 13, ' Divorced', ' Exec-managerial', ' Own-child', ' White', ' Male', 0, 1408, 40, 'America', ' <=50K'),
 (32, 30, ' Federal-gov', 59951, ' Some-college', 10, ' Married-civ-spouse', ' Adm-clerical', ' Own-child', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (33, 22, ' State-gov', 311512, ' Some-college', 10, ' Married-civ-spouse', ' Other-service', ' Husband', ' Black', ' Male', 0, 0, 15, 'America', ' <=50K'),
 (34, 48, 'Updated', 242406, ' 11th', 7, ' Never-married', ' Machine-op-inspct', ' Unmarried', ' White', ' Male', 0, 0, 40, ' Puerto-Rico', ' <=50K'),
 (35, 21, 'Updated', 197200, ' Some-college', 10, ' Never-married', ' Machine-op-inspct', ' Own-child', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (36, 19, 'Updated', 544091, ' HS-grad', 9, ' Married-AF-spouse', ' Adm-clerical', ' Wife', ' White', ' Female', 0, 0, 25, 'America', ' <=50K'),
 (37, 31, 'Updated', 84154, ' Some-college', 10, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 38, ' ?', ' >50K'),
 (38, 48, ' Self-emp-not-inc', 265477, ' Assoc-acdm', 12, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (39, 31, 'Updated', 507875, ' 9th', 5, ' Married-civ-spouse', ' Machine-op-inspct', ' Husband', ' White', ' Male', 0, 0, 43, 'America', ' <=50K'),
 (40, 53, ' Self-emp-not-inc', 88506, ' Bachelors', 13, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (41, 24, 'Updated', 172987, ' Bachelors', 13, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (42, 49, 'Updated', 94638, ' HS-grad', 9, ' Separated', ' Adm-clerical', ' Unmarried', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (43, 25, 'Updated', 289980, ' HS-grad', 9, ' Never-married', ' Handlers-cleaners', ' Not-in-family', ' White', ' Male', 0, 0, 35, 'America', ' <=50K'),
 (44, 57, ' Federal-gov', 337895, ' Bachelors', 13, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Black', ' Male', 0, 0, 40, 'America', ' >50K'),
 (45, 53, 'Updated', 144361, ' HS-grad', 9, ' Married-civ-spouse', ' Machine-op-inspct', ' Husband', ' White', ' Male', 0, 0, 38, 'America', ' <=50K'),
 (47, 41, ' State-gov', 101603, ' Assoc-voc', 11, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (48, 29, 'Updated', 271466, ' Assoc-voc', 11, ' Never-married', ' Prof-specialty', ' Not-in-family', ' White', ' Male', 0, 0, 43, 'America', ' <=50K'),
 (49, 25, 'Updated', 32275, ' Some-college', 10, ' Married-civ-spouse', ' Exec-managerial', ' Wife', ' Other', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (50, 18, 'Updated', 226956, ' HS-grad', 9, ' Never-married', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 30, ' ?', ' <=50K'),
 (51, 47, 'Updated', 51835, ' Prof-school', 15, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 0, 1902, 60, ' Honduras', ' >50K'),
 (52, 50, ' Federal-gov', 251585, ' Bachelors', 13, ' Divorced', ' Exec-managerial', ' Not-in-family', ' White', ' Male', 0, 0, 55, 'America', ' >50K'),
 (53, 47, ' Self-emp-inc', 109832, ' HS-grad', 9, ' Divorced', ' Exec-managerial', ' Not-in-family', ' White', ' Male', 0, 0, 60, 'America', ' <=50K'),
 (54, 43, 'Updated', 237993, ' Some-college', 10, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' >50K'),
 (55, 46, 'Updated', 216666, ' 5th-6th', 3, ' Married-civ-spouse', ' Machine-op-inspct', ' Husband', ' White', ' Male', 0, 0, 40, ' Mexico', ' <=50K'),
 (56, 35, 'Updated', 56352, ' Assoc-voc', 11, ' Married-civ-spouse', ' Other-service', ' Husband', ' White', ' Male', 0, 0, 40, ' Puerto-Rico', ' <=50K'),
 (57, 41, 'Updated', 147372, ' HS-grad', 9, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' White', ' Male', 0, 0, 48, 'America', ' <=50K'),
 (58, 30, 'Updated', 188146, ' HS-grad', 9, ' Married-civ-spouse', ' Machine-op-inspct', ' Husband', ' White', ' Male', 5013, 0, 40, 'America', ' <=50K'),
 (59, 30, 'Updated', 59496, ' Bachelors', 13, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 2407, 0, 40, 'America', ' <=50K'),
 (60, 32, ' ?', 293936, ' 7th-8th', 4, ' Married-spouse-absent', ' ?', ' Not-in-family', ' White', ' Male', 0, 0, 40, ' ?', ' <=50K'),
 (61, 48, 'Updated', 149640, ' HS-grad', 9, ' Married-civ-spouse', ' Transport-moving', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (62, 42, 'Updated', 116632, ' Doctorate', 16, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 45, 'America', ' >50K'),
 (63, 29, 'Updated', 105598, ' Some-college', 10, ' Divorced', ' Tech-support', ' Not-in-family', ' White', ' Male', 0, 0, 58, 'America', ' <=50K'),
 (64, 36, 'Updated', 155537, ' HS-grad', 9, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (65, 28, 'Updated', 183175, ' Some-college', 10, ' Divorced', ' Adm-clerical', ' Not-in-family', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (66, 53, 'Updated', 169846, ' HS-grad', 9, ' Married-civ-spouse', ' Adm-clerical', ' Wife', ' White', ' Female', 0, 0, 40, 'America', ' >50K'),
 (67, 49, ' Self-emp-inc', 191681, ' Some-college', 10, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' >50K'),
 (68, 25, ' ?', 200681, ' Some-college', 10, ' Never-married', ' ?', ' Own-child', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (69, 19, 'Updated', 101509, ' Some-college', 10, ' Never-married', ' Prof-specialty', ' Own-child', ' White', ' Male', 0, 0, 32, 'America', ' <=50K'),
 (70, 31, 'Updated', 309974, ' Bachelors', 13, ' Separated', ' Sales', ' Own-child', ' Black', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (71, 29, ' Self-emp-not-inc', 162298, ' Bachelors', 13, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 70, 'America', ' >50K'),
 (72, 23, 'Updated', 211678, ' Some-college', 10, ' Never-married', ' Machine-op-inspct', ' Not-in-family', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (73, 79, 'Updated', 124744, ' Some-college', 10, ' Married-civ-spouse', ' Prof-specialty', ' Other-relative', ' White', ' Male', 0, 0, 20, 'America', ' <=50K'),
 (74, 27, 'Updated', 213921, ' HS-grad', 9, ' Never-married', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 40, ' Mexico', ' <=50K'),
 (75, 40, 'Updated', 32214, ' Assoc-acdm', 12, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (76, 67, ' ?', 212759, ' 10th', 6, ' Married-civ-spouse', ' ?', ' Husband', ' White', ' Male', 0, 0, 2, 'America', ' <=50K'),
 (77, 18, 'Updated', 309634, ' 11th', 7, ' Never-married', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 22, 'America', ' <=50K'),
 (78, 31, ' Local-gov', 125927, ' 7th-8th', 4, ' Married-civ-spouse', ' Farming-fishing', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (79, 18, 'Updated', 446839, ' HS-grad', 9, ' Never-married', ' Sales', ' Not-in-family', ' White', ' Male', 0, 0, 30, 'America', ' <=50K'),
 (80, 52, 'Updated', 276515, ' Bachelors', 13, ' Married-civ-spouse', ' Other-service', ' Husband', ' White', ' Male', 0, 0, 40, ' Cuba', ' <=50K'),
 (81, 46, 'Updated', 51618, ' HS-grad', 9, ' Married-civ-spouse', ' Other-service', ' Wife', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (82, 59, 'Updated', 159937, ' HS-grad', 9, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 48, 'America', ' <=50K'),
 (83, 44, 'Updated', 343591, ' HS-grad', 9, ' Divorced', ' Craft-repair', ' Not-in-family', ' White', ' Female', 14344, 0, 40, 'America', ' >50K'),
 (84, 53, 'Updated', 346253, ' HS-grad', 9, ' Divorced', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 35, 'America', ' <=50K'),
 (85, 49, ' Local-gov', 268234, ' HS-grad', 9, ' Married-civ-spouse', ' Protective-serv', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' >50K'),
 (87, 30, 'Updated', 54334, ' 9th', 5, ' Never-married', ' Sales', ' Not-in-family', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (88, 43, ' Federal-gov', 410867, ' Doctorate', 16, ' Never-married', ' Prof-specialty', ' Not-in-family', ' White', ' Female', 0, 0, 50, 'America', ' >50K'),
 (89, 57, 'Updated', 249977, ' Assoc-voc', 11, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (90, 37, 'Updated', 286730, ' Some-college', 10, ' Divorced', ' Craft-repair', ' Unmarried', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (91, 28, 'Updated', 212563, ' Some-college', 10, ' Divorced', ' Machine-op-inspct', ' Unmarried', ' Black', ' Female', 0, 0, 25, 'America', ' <=50K'),
 (92, 30, 'Updated', 117747, ' HS-grad', 9, ' Married-civ-spouse', ' Sales', ' Wife', ' Asian-Pac-Islander', ' Female', 0, 1573, 35, ' ?', ' <=50K'),
 (93, 34, ' Local-gov', 226296, ' Bachelors', 13, ' Married-civ-spouse', ' Protective-serv', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' >50K'),
 (94, 29, ' Local-gov', 115585, ' Some-college', 10, ' Never-married', ' Handlers-cleaners', ' Not-in-family', ' White', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (95, 48, ' Self-emp-not-inc', 191277, ' Doctorate', 16, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 1902, 60, 'America', ' >50K'),
 (96, 37, 'Updated', 202683, ' Some-college', 10, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 48, 'America', ' >50K'),
 (97, 48, 'Updated', 171095, ' Assoc-acdm', 12, ' Divorced', ' Exec-managerial', ' Unmarried', ' White', ' Female', 0, 0, 40, ' England', ' <=50K'),
 (98, 32, ' Federal-gov', 249409, ' HS-grad', 9, ' Never-married', ' Other-service', ' Own-child', ' Black', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (100, 44, 'Updated', 198282, ' Bachelors', 13, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 60, 'America', ' >50K'),
 (102, 20, 'Updated', 188300, ' Some-college', 10, ' Never-married', ' Tech-support', ' Own-child', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (103, 29, 'Updated', 103432, ' HS-grad', 9, ' Never-married', ' Craft-repair', ' Not-in-family', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (104, 32, ' Self-emp-inc', 317660, ' HS-grad', 9, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 7688, 0, 40, 'America', ' >50K'),
 (105, 17, ' ?', 304873, ' 10th', 6, ' Never-married', ' ?', ' Own-child', ' White', ' Female', 34095, 0, 32, 'America', ' <=50K'),
 (106, 30, 'Updated', 194901, ' 11th', 7, ' Never-married', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (107, 31, ' Local-gov', 189265, ' HS-grad', 9, ' Never-married', ' Adm-clerical', ' Not-in-family', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (108, 42, 'Updated', 124692, ' HS-grad', 9, ' Married-civ-spouse', ' Handlers-cleaners', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (109, 24, 'Updated', 432376, ' Bachelors', 13, ' Never-married', ' Sales', ' Other-relative', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (110, 38, 'Updated', 65324, ' Prof-school', 15, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' >50K'),
 (111, 56, ' Self-emp-not-inc', 335605, ' HS-grad', 9, ' Married-civ-spouse', ' Other-service', ' Husband', ' White', ' Male', 0, 1887, 50, ' Canada', ' >50K'),
 (112, 28, 'Updated', 377869, ' Some-college', 10, ' Married-civ-spouse', ' Sales', ' Wife', ' White', ' Female', 4064, 0, 25, 'America', ' <=50K'),
 (113, 36, 'Updated', 102864, ' HS-grad', 9, ' Never-married', ' Machine-op-inspct', ' Own-child', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (114, 53, 'Updated', 95647, ' 9th', 5, ' Married-civ-spouse', ' Handlers-cleaners', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (115, 56, ' Self-emp-inc', 303090, ' Some-college', 10, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (116, 49, ' Local-gov', 197371, ' Assoc-voc', 11, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' Black', ' Male', 0, 0, 40, 'America', ' >50K'),
 (117, 55, 'Updated', 247552, ' Some-college', 10, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 56, 'America', ' <=50K'),
 (118, 22, 'Updated', 102632, ' HS-grad', 9, ' Never-married', ' Craft-repair', ' Not-in-family', ' White', ' Male', 0, 0, 41, 'America', ' <=50K'),
 (119, 21, 'Updated', 199915, ' Some-college', 10, ' Never-married', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),
 (120, 40, 'Updated', 118853, ' Bachelors', 13, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 60, 'America', ' <=50K'),
 (121, 30, 'Updated', 77143, ' Bachelors', 13, ' Never-married', ' Exec-managerial', ' Own-child', ' Black', ' Male', 0, 0, 40, ' Germany', ' <=50K'),
 (122, 29, ' State-gov', 267989, ' Bachelors', 13, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' >50K'),
 (123, 19, 'Updated', 301606, ' Some-college', 10, ' Never-married', ' Other-service', ' Own-child', ' Black', ' Male', 0, 0, 35, 'America', ' <=50K'),
 (124, 47, 'Updated', 287828, ' Bachelors', 13, ' Married-civ-spouse', ' Exec-managerial', ' Wife', ' White', ' Female', 0, 0, 40, 'America', ' >50K'),
 (125, 20, 'Updated', 111697, ' Some-college', 10, ' Never-married', ' Adm-clerical', ' Own-child', ' White', ' Female', 0, 1719, 28, 'America', ' <=50K'),
 (126, 31, 'Updated', 114937, ' Assoc-acdm', 12, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' >50K'),
 (127, 35, ' ?', 129305, ' HS-grad', 9, ' Married-civ-spouse', ' ?', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (128, 39, 'Updated', 365739, ' Some-college', 10, ' Divorced', ' Craft-repair', ' Not-in-family', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (129, 28, 'Updated', 69621, ' Assoc-acdm', 12, ' Never-married', ' Sales', ' Not-in-family', ' White', ' Female', 0, 0, 60, 'America', ' <=50K'),
 (130, 24, 'Updated', 43323, ' HS-grad', 9, ' Never-married', ' Other-service', ' Not-in-family', ' White', ' Female', 0, 1762, 40, 'America', ' <=50K'),
 (131, 38, ' Self-emp-not-inc', 120985, ' HS-grad', 9, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 4386, 0, 35, 'America', ' <=50K'),
 (132, 37, 'Updated', 254202, ' Bachelors', 13, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 50, 'America', ' <=50K'),
 (133, 46, 'Updated', 146195, ' Assoc-acdm', 12, ' Divorced', ' Tech-support', ' Not-in-family', ' Black', ' Female', 0, 0, 36, 'America', ' <=50K'),
 (135, 43, ' Self-emp-not-inc', 56920, ' HS-grad', 9, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 0, 0, 60, 'America', ' <=50K'),
 (136, 27, 'Updated', 163127, ' Assoc-voc', 11, ' Married-civ-spouse', ' Adm-clerical', ' Wife', ' White', ' Female', 0, 0, 35, 'America', ' <=50K'),
 (137, 20, 'Updated', 34310, ' Some-college', 10, ' Never-married', ' Sales', ' Own-child', ' White', ' Male', 0, 0, 20, 'America', ' <=50K'),
 (138, 49, 'Updated', 81973, ' Some-college', 10, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 40, 'America', ' >50K'),
 (139, 61, ' Self-emp-inc', 66614, ' HS-grad', 9, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 0, 0, 40, 'America', ' <=50K'),
 (140, 27, 'Updated', 232782, ' Some-college', 10, ' Never-married', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 40, 'America', ' <=50K'),

In [18]:
print('\n 4. Write two filter queries \n','-'*35, sep='')

engine.execute("SELECT race, COUNT(*) AS Total FROM sqladb GROUP BY race;").fetchall()

 4. Write two filter queries
-----------------------------------

[(' Amer-Indian-Eskimo', 306),
 (' Asian-Pac-Islander', 951),
 (' Black', 3038),
 (' Other', 264),
 (' White', 26278)]

In [25]:
print("\n 5. First function query (Working hours as per Occupation) \n",'-'*65, sep='')

def workhrs():
    
    connection  = sqlite3.connect("sqladb")
    cursor = connection.cursor()
           
    return engine.execute('SELECT education, hours_per_week FROM sqladb GROUP BY education ').fetchall()

workhrs()

 5. First function query (Working hours as per Occupation)
-----------------------------------------------------------------

[(' 10th', 40),
 (' 11th', 40),
 (' 12th', 35),
 (' 1st-4th', 35),
 (' 5th-6th', 40),
 (' 7th-8th', 40),
 (' 9th', 40),
 (' Assoc-acdm', 38),
 (' Assoc-voc', 45),
 (' Bachelors', 45),
 (' Doctorate', 10),
 (' HS-grad', 40),
 (' Preschool', 72),
 (' Prof-school', 60),
 (' Some-college', 40)]

In [22]:
 print("\n 5. Second function query (Average age for getting married) \n",'-'*65, sep='')

def maritalage():
    
    connection  = sqlite3.connect("sqladb")
    cursor = connection.cursor()
    
    return engine.execute('SELECT marital_status, avg(age) FROM sqladb GROUP BY marital_status ').fetchall()

maritalage()

 5. Second function query (Average age for getting married)
-----------------------------------------------------------------

[(' Divorced', 42.807125890736344),
 (' Married-AF-spouse', 32.47826086956522),
 (' Married-civ-spouse', 43.110713518929366),
 (' Married-spouse-absent', 40.266832917705734),
 (' Never-married', 27.76979957190115),
 (' Separated', 39.233),
 (' Widowed', 59.003151260504204)]

In [23]:
cursor.close()
connection.close()